tokens = {
    "(": "PLEFT",
    ")": "PRIGHT",
    "{": "CLEFT",
    "}": "CRIGHT",
    "+": "ADD",
    "-": "SUB",
    "*": "MULT",
    "/": "DIV",
    ",": "COMMA",
    ";": "SEMICOLON",
    "v": "VAR_ID",
    "f": "FUNC_ID",
    "p": "PROC_ID",
    "id": "ID",
    "num": "NUM",
    "word": "WORD"
}

tokensPalavrasReservadas = {
    "program": "PROGRAM",
    "end": "END",
    "func": "FUNC",
    "proc": "PROC",
    "call": "CALL",
    "int": "INT",
    "boolean": "BOOLEAN",
    "string": "STRING",
    "true": "BOOL",
    "false": "BOOL",
    "return": "RETURN",
    "if": "IF",
    "endif": "ENDIF",
    "else": "ELSE",
    "endelse": "ENDELSE",
    "while": "WHILE",
    "endwhile": "ENDWHILE",
    "print": "PRINT",
    "break": "BREAK",
    "continue": "CONTINUE",
}